// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Belt_Debug = require("bs-platform/lib/js/belt_Debug.js");

Belt_Debug.setupChromeDebugger(/* () */0);

/*  Not a pure module */
