// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Belt_Map = require("bs-platform/lib/js/belt_Map.js");
var Belt_MapString = require("bs-platform/lib/js/belt_MapString.js");
var Definition$ReactTemplate = require("../Definition.bs.js");
var ColumnizeNodes$ReactTemplate = require("../display/ColumnizeNodes.bs.js");

function detectCycles(connections, nodes) {
  try {
    ColumnizeNodes$ReactTemplate.columnizeNodes(nodes, connections);
    return false;
  }
  catch (exn){
    if (exn === Definition$ReactTemplate.CycleDetected) {
      return true;
    } else {
      throw exn;
    }
  }
}

function isParentScope(parent, _child, nodes) {
  while(true) {
    var child = _child;
    if (parent === child) {
      return true;
    } else {
      var match = Belt_MapString.getExn(nodes, child)[/* scope */0];
      if (match) {
        _child = match[0];
        continue ;
      } else {
        return false;
      }
    }
  };
}

function checkConnectionScope(source, sink, nodes) {
  var match = sink[/* node */0];
  var match$1 = source[/* node */0];
  if (match$1) {
    if (match) {
      var sourceNodeID = match$1[0];
      var sinkNodeID = match[0];
      var sinkNode = Belt_MapString.getExn(nodes, sinkNodeID);
      var sourceNode = Belt_MapString.getExn(nodes, sourceNodeID);
      if (sourceNodeID === sinkNodeID) {
        if (Definition$ReactTemplate.isFunctionDefinitionNode(sourceNode) && Definition$ReactTemplate.isKeywordNib(source[/* nib */1]) && Definition$ReactTemplate.isFunctionDefinitionNode(sinkNode)) {
          return Definition$ReactTemplate.isKeywordNib(sink[/* nib */1]);
        } else {
          return false;
        }
      } else if (Definition$ReactTemplate.isFunctionDefinitionNode(sourceNode) && Definition$ReactTemplate.isKeywordNib(source[/* nib */1])) {
        if (sourceNodeID === sinkNodeID) {
          return Definition$ReactTemplate.isKeywordNib(sink[/* nib */1]);
        } else {
          var match$2 = sinkNode[/* scope */0];
          if (match$2) {
            return isParentScope(sourceNodeID, match$2[0], nodes);
          } else {
            return sourceNodeID === sinkNodeID;
          }
        }
      } else {
        var match$3 = sourceNode[/* scope */0];
        if (match$3) {
          var sourceScopeNodeID = match$3[0];
          if (sourceScopeNodeID === sinkNodeID) {
            return true;
          } else {
            var match$4 = sinkNode[/* scope */0];
            if (match$4) {
              return isParentScope(sourceScopeNodeID, match$4[0], nodes);
            } else {
              return false;
            }
          }
        } else {
          return true;
        }
      }
    } else {
      return Belt_MapString.getExn(nodes, match$1[0])[/* scope */0] === /* GraphScope */0;
    }
  } else {
    return true;
  }
}

function checkScopes(connections, nodes) {
  return !Belt_Map.some(connections, (function (sink, source) {
                return !checkConnectionScope(source, sink, nodes);
              }));
}

exports.detectCycles = detectCycles;
exports.isParentScope = isParentScope;
exports.checkConnectionScope = checkConnectionScope;
exports.checkScopes = checkScopes;
/* Definition-ReactTemplate Not a pure module */
