// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Belt_MapString = require("bs-platform/lib/js/belt_MapString.js");
var NibsBox$ReactTemplate = require("./NibsBox.bs.js");
var Definition$ReactTemplate = require("../Definition.bs.js");
var DefinitionBox$ReactTemplate = require("./DefinitionBox.bs.js");

var component = ReasonReact.statelessComponent("Node");

function make(node, definitions, position, size, nodeWidth, textHeight, $staropt$star, onClick, onMouseDown, onTouchStart, onMouseUp, onTouchEnd, _children) {
  var selected = $staropt$star !== undefined ? $staropt$star : false;
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var makeNode = function (name, onDoubleClick) {
                return ReasonReact.element(undefined, undefined, NibsBox$ReactTemplate.make(name, position, size[/* y */1], nodeWidth, textHeight, selected, onDoubleClick, onClick, onMouseDown, onTouchStart, onMouseUp, onTouchEnd, /* array */[]));
              };
              var match = node[/* kind */1];
              if (typeof match === "number") {
                return makeNode("Reference", undefined);
              } else if (match.tag) {
                var definitionID = match[0][/* definitionID */1];
                var definition = Belt_MapString.getExn(definitions, definitionID);
                var name = Definition$ReactTemplate.getDisplayName(definition, "en");
                var onDoubleClick = function (_event) {
                  return ReasonReact.Router[/* push */0]("#" + definitionID);
                };
                if (Definition$ReactTemplate.isFunctionDefinitionNode(node)) {
                  return ReasonReact.element(undefined, undefined, DefinitionBox$ReactTemplate.make(name, position, size, nodeWidth, textHeight, selected, onClick, onDoubleClick, onMouseDown, onTouchStart, onMouseUp, onTouchEnd, /* array */[]));
                } else {
                  return makeNode(name, onDoubleClick);
                }
              } else {
                return makeNode("List", undefined);
              }
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
