// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var Belt_Debug = require("bs-platform/lib/js/belt_Debug.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Definition$ReactTemplate = require("../Definition.bs.js");
var DefinitionHeader$ReactTemplate = require("./DefinitionHeader.bs.js");
var ConstantImplementation$ReactTemplate = require("./ConstantImplementation.bs.js");
var InterfaceImplementation$ReactTemplate = require("./InterfaceImplementation.bs.js");
var RecordTypeImplementation$ReactTemplate = require("./RecordTypeImplementation.bs.js");

Belt_Debug.setupChromeDebugger(/* () */0);

var component = ReasonReact.statelessComponent("SimpleDefinition");

function make(definitionID, definition, definitions, error, emit, _children) {
  return /* record */Block.record([
            "debugName",
            "reactClassInternal",
            "handedOffState",
            "willReceiveProps",
            "didMount",
            "didUpdate",
            "willUnmount",
            "willUpdate",
            "shouldUpdate",
            "render",
            "initialState",
            "retainedProps",
            "reducer",
            "jsElementWrapped"
          ], [
            component[/* debugName */0],
            component[/* reactClassInternal */1],
            component[/* handedOffState */2],
            component[/* willReceiveProps */3],
            component[/* didMount */4],
            component[/* didUpdate */5],
            component[/* willUnmount */6],
            component[/* willUpdate */7],
            component[/* shouldUpdate */8],
            (function (_self) {
                var display = definition[/* display */2];
                var documentation = definition[/* documentation */1];
                var implementation = definition[/* implementation */0];
                var tmp;
                switch (implementation.tag | 0) {
                  case 0 : 
                      tmp = ReasonReact.element(undefined, undefined, ConstantImplementation$ReactTemplate.make(implementation[0], emit, /* array */[]));
                      break;
                  case 1 : 
                      tmp = ReasonReact.element(undefined, undefined, InterfaceImplementation$ReactTemplate.make(definitions, implementation[0], documentation, display, emit, /* array */[]));
                      break;
                  case 4 : 
                      tmp = ReasonReact.element(undefined, undefined, RecordTypeImplementation$ReactTemplate.make(definitions, implementation[0], documentation, display, emit, /* array */[]));
                      break;
                  default:
                    tmp = "TODO";
                }
                return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, DefinitionHeader$ReactTemplate.make(definitionID, definitions, documentation, "(nameless " + (Definition$ReactTemplate.implementationName(implementation) + ")"), emit, error, /* array */[])), tmp);
              }),
            component[/* initialState */10],
            component[/* retainedProps */11],
            component[/* reducer */12],
            component[/* jsElementWrapped */13]
          ]);
}

exports.component = component;
exports.make = make;
/*  Not a pure module */
