// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

function encodePrimitiveValue(primitiveValue) {
  var tmp;
  switch (primitiveValue.tag | 0) {
    case 0 : 
        tmp = /* :: */[
          /* tuple */[
            "type",
            "integer"
          ],
          /* :: */[
            /* tuple */[
              "value",
              primitiveValue[0]
            ],
            /* [] */0
          ]
        ];
        break;
    case 1 : 
        tmp = /* :: */[
          /* tuple */[
            "type",
            "number"
          ],
          /* :: */[
            /* tuple */[
              "value",
              primitiveValue[0]
            ],
            /* [] */0
          ]
        ];
        break;
    case 2 : 
        tmp = /* :: */[
          /* tuple */[
            "type",
            "text"
          ],
          /* :: */[
            /* tuple */[
              "value",
              primitiveValue[0]
            ],
            /* [] */0
          ]
        ];
        break;
    
  }
  return Json_encode.object_(tmp);
}

function encodeCanonicalConstant(primitiveValue) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "type",
                "constant"
              ],
              /* :: */[
                /* tuple */[
                  "value",
                  encodePrimitiveValue(primitiveValue)
                ],
                /* [] */0
              ]
            ]);
}

exports.encodePrimitiveValue = encodePrimitiveValue;
exports.encodeCanonicalConstant = encodeCanonicalConstant;
/* No side effect */
