// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var CanonicalizeType$ReactTemplate = require("./CanonicalizeType.bs.js");
var CanonicalizeGraph$ReactTemplate = require("./CanonicalizeGraph.bs.js");
var CanonicalizeConstant$ReactTemplate = require("./CanonicalizeConstant.bs.js");

function canonicalizeImplementation(id, implementation, display, dependencies) {
  var tmp;
  switch (implementation.tag | 0) {
    case 0 : 
        tmp = CanonicalizeConstant$ReactTemplate.encodeCanonicalConstant(implementation[0]);
        break;
    case 1 : 
        tmp = CanonicalizeType$ReactTemplate.encodeCanonicalInterface(implementation[0], dependencies, display);
        break;
    case 2 : 
        tmp = CanonicalizeType$ReactTemplate.encodeCanonicalExternal(implementation[0], dependencies, display);
        break;
    case 3 : 
        tmp = CanonicalizeGraph$ReactTemplate.encodeCanonicalGraph(implementation[0], dependencies, display);
        break;
    case 4 : 
        tmp = CanonicalizeType$ReactTemplate.encodeCanonicalRecordType(implementation[0], dependencies, display[/* inputOrdering */0]);
        break;
    case 5 : 
        tmp = CanonicalizeType$ReactTemplate.encodeCanonicalLabeledType(id, implementation[0], dependencies);
        break;
    case 6 : 
        tmp = CanonicalizeType$ReactTemplate.encodeCanonicalUnionType(implementation[0], dependencies, display[/* inputOrdering */0]);
        break;
    
  }
  return Json.stringify(tmp);
}

exports.canonicalizeImplementation = canonicalizeImplementation;
/* CanonicalizeGraph-ReactTemplate Not a pure module */
