// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Helpers$ReactTemplate = require("./Helpers.bs.js");
var Definition$ReactTemplate = require("./Definition.bs.js");

var component = ReasonReact.statelessComponent("DefinitionList");

function make(definitions, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("ul", undefined, Helpers$ReactTemplate.renderStringMap((function (param) {
                                var definitionID = param[0];
                                return React.createElement("li", {
                                            key: definitionID
                                          }, React.createElement("a", {
                                                href: "#" + definitionID
                                              }, Definition$ReactTemplate.getTranslated(param[1][/* documentation */1][/* name */0], "en")));
                              }), definitions));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
