// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function sortBy(list, func) {
  return Belt_List.map(Belt_List.sort(Belt_List.map(list, (function (item) {
                        return /* tuple */[
                                Curry._1(func, item),
                                item
                              ];
                      })), Caml_obj.caml_compare), (function (prim) {
                return prim[1];
              }));
}

exports.sortBy = sortBy;
/* No side effect */
