// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Belt_Map = require("bs-platform/lib/js/belt_Map.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_MapString = require("bs-platform/lib/js/belt_MapString.js");

function canonicalizeOutputConnection(graph, dependencies, connectionSink) {
  var match = Belt_Map.get(graph[/* connections */0], connectionSink);
  if (match) {
    var node = match[0][/* node */0];
    if (node) {
      var nodeID = node[0];
      var match$1 = Belt_MapString.getExn(graph[/* nodes */1], nodeID);
      if (match$1) {
        var match$2 = match$1[0];
        var dependency = Belt_MapString.getExn(dependencies, match$2[/* definitionID */1]);
        return /* OutputOrderingNode */[/* record */[
                  /* contentID */dependency[/* contentID */0],
                  /* kind */match$2[/* kind */0],
                  /* children */Belt_List.map(dependency[/* inputOrdering */1], (function (nibID) {
                          return canonicalizeOutputConnection(graph, dependencies, /* record */[
                                      /* node : NodeConnection */[nodeID],
                                      /* nib : NibConnection */[nibID]
                                    ]);
                        }))
                ]];
      } else {
        return /* OutputOrderingReference */2;
      }
    } else {
      return /* OutputOrderingInput */1;
    }
  } else {
    return /* OutputOrderingDisconnected */0;
  }
}

function canonicalizeOutput(graph, dependencies, nibID) {
  return canonicalizeOutputConnection(graph, dependencies, /* record */[
              /* node : GraphConnection */0,
              /* nib : NibConnection */[nibID]
            ]);
}

exports.canonicalizeOutputConnection = canonicalizeOutputConnection;
exports.canonicalizeOutput = canonicalizeOutput;
/* No side effect */
